const emailDatabase = [
  // --- EASY LEVEL ---
  {
    "id": "leg_001",
    "subject": "Your Monthly Bank Statement is Ready",
    "sender": "alerts@gtbank.com",
    "body": "Dear David, your monthly account statement is now available. Please log into your banking app to review.",
    "label": "legitimate",
    "timestamp": "2026-04-01T09:15:00Z",
    "sender_domain": "gtbank.com",
    "urgency_level": "low",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_002",
    "subject": "Order Confirmation #45231",
    "sender": "orders@jumia.com",
    "body": "Hi David, your order has been successfully placed. You will receive delivery updates shortly.",
    "label": "legitimate",
    "timestamp": "2026-04-02T14:20:00Z",
    "sender_domain": "jumia.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_005",
    "subject": "Welcome to Netflix",
    "sender": "info@netflix.com",
    "body": "Welcome! Your subscription has been activated. Enjoy unlimited movies and series.",
    "label": "legitimate",
    "timestamp": "2026-04-05T11:00:00Z",
    "sender_domain": "netflix.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_007",
    "subject": "Meeting Reminder - Project Discussion",
    "sender": "hr@company.com",
    "body": "This is a reminder for your scheduled meeting tomorrow at 10 AM.",
    "label": "legitimate",
    "timestamp": "2026-04-07T16:00:00Z",
    "sender_domain": "company.com",
    "urgency_level": "low",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_010",
    "subject": "Weekly Newsletter",
    "sender": "newsletter@techcrunch.com",
    "body": "Here are this week’s top tech stories and insights.",
    "label": "legitimate",
    "timestamp": "2026-04-10T08:00:00Z",
    "sender_domain": "techcrunch.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_012",
    "subject": "Flight Booking Confirmation",
    "sender": "tickets@airpeace.com",
    "body": "Your flight has been successfully booked. Check your itinerary for details.",
    "label": "legitimate",
    "timestamp": "2026-04-12T10:30:00Z",
    "sender_domain": "airpeace.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_015",
    "subject": "Your Ride Receipt",
    "sender": "receipts@uber.com",
    "body": "Thanks for riding with us. Here is your trip summary and fare breakdown.",
    "label": "legitimate",
    "timestamp": "2026-04-15T22:45:00Z",
    "sender_domain": "uber.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_016",
    "subject": "Course Enrollment Successful",
    "sender": "noreply@coursera.org",
    "body": "You have successfully enrolled in your selected course.",
    "label": "legitimate",
    "timestamp": "2026-04-16T06:50:00Z",
    "sender_domain": "coursera.org",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_017",
    "subject": "Maintenance Notice",
    "sender": "support@bank.com",
    "body": "Our services will be temporarily unavailable due to scheduled maintenance.",
    "label": "legitimate",
    "timestamp": "2026-04-17T23:00:00Z",
    "sender_domain": "bank.com",
    "urgency_level": "low",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_019",
    "subject": "Your Mobile Data Plan Renewal Successful",
    "sender": "notifications@mtn.ng",
    "body": "Dear Customer, your data subscription has been successfully renewed. You can continue enjoying uninterrupted internet access.",
    "label": "legitimate",
    "timestamp": "2026-04-19T08:40:00Z",
    "sender_domain": "mtn.ng",
    "urgency_level": "low",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_020",
    "subject": "Job Application Received",
    "sender": "careers@flutterwave.com",
    "body": "Hi David, we have received your job application. Our team will review it and get back to you shortly.",
    "label": "legitimate",
    "timestamp": "2026-04-20T13:10:00Z",
    "sender_domain": "flutterwave.com",
    "urgency_level": "low",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_021",
    "subject": "Your Receipt from Shoprite",
    "sender": "receipts@shoprite.com",
    "body": "Hi David, thank you for shopping with us. Your receipt is attached for your recent purchase.",
    "label": "legitimate",
    "timestamp": "2026-04-21T10:15:00Z",
    "sender_domain": "shoprite.com",
    "urgency_level": "low",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_022",
    "subject": "Gym Membership Renewal Confirmation",
    "sender": "support@fitnessplus.com",
    "body": "Your gym membership has been successfully renewed. We look forward to seeing you.",
    "label": "legitimate",
    "timestamp": "2026-04-22T08:00:00Z",
    "sender_domain": "fitnessplus.com",
    "urgency_level": "low",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_023",
    "subject": "Library Book Due Reminder",
    "sender": "notifications@library.org",
    "body": "This is a reminder that your borrowed book is due in 3 days. Please return or renew it.",
    "label": "legitimate",
    "timestamp": "2026-04-23T12:30:00Z",
    "sender_domain": "library.org",
    "urgency_level": "low",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },
  {
    "id": "leg_024",
    "subject": "Your Subscription Has Been Activated",
    "sender": "info@canva.com",
    "body": "Welcome! Your premium subscription is now active. Enjoy all features available on your plan.",
    "label": "legitimate",
    "timestamp": "2026-04-24T09:45:00Z",
    "sender_domain": "canva.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "easy"
  },

  // --- MEDIUM LEVEL ---
  {
    "id": "leg_004",
    "subject": "Your Electricity Bill for April",
    "sender": "billing@ikejaelectric.com",
    "body": "Dear Customer, your electricity bill is ready. Kindly log into your official account portal to view details.",
    "label": "legitimate",
    "timestamp": "2026-04-04T07:30:00Z",
    "sender_domain": "ikejaelectric.com",
    "urgency_level": "low",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_006",
    "subject": "Shipment Update: Package in Transit",
    "sender": "updates@dhl.com",
    "body": "Your package is currently in transit and will be delivered soon. Track via the official DHL website.",
    "label": "legitimate",
    "timestamp": "2026-04-06T13:45:00Z",
    "sender_domain": "dhl.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_008",
    "subject": "Payment Received Successfully",
    "sender": "no-reply@paypal.com",
    "body": "You have received a payment. Check your PayPal account for details.",
    "label": "legitimate",
    "timestamp": "2026-04-08T12:10:00Z",
    "sender_domain": "paypal.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_013",
    "subject": "Subscription Renewal Reminder",
    "sender": "billing@spotify.com",
    "body": "Your subscription will renew soon. Ensure your payment method is valid.",
    "label": "legitimate",
    "timestamp": "2026-04-13T15:20:00Z",
    "sender_domain": "spotify.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_025",
    "subject": "Invoice Available for Your Recent Purchase",
    "sender": "billing@konga.com",
    "body": "Dear David, your invoice is ready. Please visit your account dashboard to view details.",
    "label": "legitimate",
    "timestamp": "2026-04-25T14:10:00Z",
    "sender_domain": "konga.com",
    "urgency_level": "medium",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_026",
    "subject": "Your Account Balance Update",
    "sender": "alerts@accessbank.com",
    "body": "Your account balance has been updated. Kindly check your banking app for recent transactions.",
    "label": "legitimate",
    "timestamp": "2026-04-26T07:25:00Z",
    "sender_domain": "accessbank.com",
    "urgency_level": "medium",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_027",
    "subject": "Delivery Attempt Notification",
    "sender": "support@fedex.com",
    "body": "We attempted delivery but could not reach you. Please reschedule via our official website.",
    "label": "legitimate",
    "timestamp": "2026-04-27T16:40:00Z",
    "sender_domain": "fedex.com",
    "urgency_level": "medium",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_028",
    "subject": "Action Required: Update Your Profile Information",
    "sender": "support@linkedin.com",
    "body": "Hi David, please review and update your profile information to keep your account up to date.",
    "label": "legitimate",
    "timestamp": "2026-04-28T11:15:00Z",
    "sender_domain": "linkedin.com",
    "urgency_level": "medium",
    "contains_link": true,
    "social_engineering_type": "authority",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_029",
    "subject": "Reminder: Payment Due Soon",
    "sender": "billing@dstv.com",
    "body": "Your subscription payment is due soon. Please ensure your account is funded to avoid interruption.",
    "label": "legitimate",
    "timestamp": "2026-04-29T18:00:00Z",
    "sender_domain": "dstv.com",
    "urgency_level": "medium",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_030",
    "subject": "Security Notice: New Device Login",
    "sender": "security@instagram.com",
    "body": "We detected a login from a new device. If this was you, no action is needed.",
    "label": "legitimate",
    "timestamp": "2026-04-30T20:10:00Z",
    "sender_domain": "instagram.com",
    "urgency_level": "medium",
    "contains_link": false,
    "social_engineering_type": "security_alert",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_031",
    "subject": "Update Your Payment Method",
    "sender": "billing@apple.com",
    "body": "There was an issue with your payment method. Please update it via your account settings.",
    "label": "legitimate",
    "timestamp": "2026-05-01T09:00:00Z",
    "sender_domain": "apple.com",
    "urgency_level": "medium",
    "contains_link": true,
    "social_engineering_type": "authority",
    "difficulty_level": "medium"
  },
  {
    "id": "leg_032",
    "subject": "Course Progress Update",
    "sender": "updates@udemy.com",
    "body": "You have made progress in your enrolled course. Continue learning to complete your certification.",
    "label": "legitimate",
    "timestamp": "2026-05-02T13:30:00Z",
    "sender_domain": "udemy.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "none",
    "difficulty_level": "medium"
  },

  // --- DIFFICULT LEVEL ---
  {
    "id": "leg_003",
    "subject": "Password Changed Successfully",
    "sender": "security@google.com",
    "body": "Your password was changed successfully. If this wasn’t you, please secure your account immediately.",
    "label": "legitimate",
    "timestamp": "2026-04-03T18:05:00Z",
    "sender_domain": "google.com",
    "urgency_level": "medium",
    "contains_link": false,
    "social_engineering_type": "security_alert",
    "difficulty_level": "difficult"
  },
  {
    "id": "leg_009",
    "subject": "University Admission Update",
    "sender": "admissions@unilag.edu.ng",
    "body": "Your application status has been updated. Please log into the student portal.",
    "label": "legitimate",
    "timestamp": "2026-04-09T09:00:00Z",
    "sender_domain": "unilag.edu.ng",
    "urgency_level": "medium",
    "contains_link": false,
    "social_engineering_type": "none",
    "difficulty_level": "difficult"
  },
  {
    "id": "leg_011",
    "subject": "Account Login Alert",
    "sender": "security@facebook.com",
    "body": "We noticed a new login to your account from a new device.",
    "label": "legitimate",
    "timestamp": "2026-04-11T21:15:00Z",
    "sender_domain": "facebook.com",
    "urgency_level": "medium",
    "contains_link": false,
    "social_engineering_type": "security_alert",
    "difficulty_level": "difficult"
  },
  {
    "id": "leg_014",
    "subject": "Password Reset Request",
    "sender": "no-reply@amazon.com",
    "body": "We received a request to reset your password. If this was not you, ignore this message.",
    "label": "legitimate",
    "timestamp": "2026-04-14T19:00:00Z",
    "sender_domain": "amazon.com",
    "urgency_level": "medium",
    "contains_link": true,
    "social_engineering_type": "security_alert",
    "difficulty_level": "difficult"
  },
  {
    "id": "leg_033",
    "subject": "Unusual Activity Detected on Your Account",
    "sender": "security@amaz0n.com",
    "body": "Hi David, we noticed unusual activity. Please review your account activity to ensure everything is secure.",
    "label": "legitimate",
    "timestamp": "2026-05-03T17:20:00Z",
    "sender_domain": "amaz0n.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "authority",
    "difficulty_level": "difficult"
  },
  {
    "id": "leg_034",
    "subject": "Verify Your Account Information",
    "sender": "support@micros0ft.com",
    "body": "We recommend verifying your account details to maintain uninterrupted service.",
    "label": "legitimate",
    "timestamp": "2026-05-04T08:10:00Z",
    "sender_domain": "micros0ft.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "authority",
    "difficulty_level": "difficult"
  },
  {
    "id": "leg_035",
    "subject": "Important: Review Your Recent Activity",
    "sender": "alerts@paypaI.com",
    "body": "A recent transaction was flagged for review. Please check your account activity for confirmation.",
    "label": "legitimate",
    "timestamp": "2026-05-05T12:00:00Z",
    "sender_domain": "paypaI.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "authority",
    "difficulty_level": "difficult"
  },
  {
    "id": "leg_036",
    "subject": "Login Attempt Notification",
    "sender": "security@faceb00k.com",
    "body": "We detected a login attempt from an unfamiliar device. Please review your login history.",
    "label": "legitimate",
    "timestamp": "2026-05-06T21:30:00Z",
    "sender_domain": "faceb00k.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "security_alert",
    "difficulty_level": "difficult"
  },
  {
    "id": "leg_037",
    "subject": "Confirm Your Identity",
    "sender": "no-reply@bank-secure.com",
    "body": "To continue using your account, please confirm your identity through the official portal.",
    "label": "legitimate",
    "timestamp": "2026-05-07T15:45:00Z",
    "sender_domain": "bank-secure.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "authority",
    "difficulty_level": "difficult"
  },
  {
    "id": "leg_038",
    "subject": "Security Update Required",
    "sender": "security@goog1e.com",
    "body": "We recommend updating your security settings to enhance account protection.",
    "label": "legitimate",
    "timestamp": "2026-05-08T10:05:00Z",
    "sender_domain": "goog1e.com",
    "urgency_level": "low",
    "contains_link": true,
    "social_engineering_type": "authority",
    "difficulty_level": "difficult"
  }
];